### ISSUE TITLE
Adding integration test

### ISSUE THREAD

**Issue by jeswr** [CommunitySolidServer/hello-world-component#1]
Would a copy/paste of this file serve as a suitable demonstration for integration testing https://github.com/comunica/comunica/blob/e86e96a68965e09d909fa56f95e10a13c38b90b0/engines/query-sparql/test/Solid-test.ts

**Comment by joachimvh** [comment]
I was going to add an integration test here myself so I could also update all the relevant documentation in the readme here and explain all the steps in the test, but then I got distracted by something else. I'll just do it now.

**Comment by joachimvh** [comment]
Done in https://github.com/CommunitySolidServer/hello-world-component/commit/d3ee3608e8d0217be1d90a797fcb12db75157805
