### ISSUE TITLE
new injected component running with the CSS

### ISSUE THREAD

**Issue by RezMosa** [CommunitySolidServer/hello-world-component#3]
Hello I injected a new component into a local CSS through using Component.js and your guideline. Thanks for that. My new component will be run with CSS.
Currently I have an old local hosted CSS that is running without my new component that includes some PODs.
My concern is how to run my new injected component with the old CSS that is running now? Anytime I run new injected component It will be run with a new CSS. I don't want to lose my data resources in old CSS. Thanks for your help.

**Comment by joachimvh** [comment]
If your new component doesn't change anything about how data is stored, you can just stop the old server and start a new server with the new config pointing to the same data. This is assuming that you are using a file-based backend. So specifically provide the same value to the `-f` parameter.

**Comment by RezMosa** [comment]
Thank you for your quick reply. One more question: Is it feasible to define our new app as a component to the old running CSS (without stop or restart CSS)? I meant users with their own running CSS can add our new component. Thank you.

**Comment by joachimvh** [comment]
> without stop or restart CSS

No that is not possible. The only way to load a new configuration is by restarting the server.
